---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Start dan enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Pastikan Nginx berjalan
  uri:
    url: "http://localhost"
    status_code: 200
  register: result
  retries: 3
  delay: 5
